# Theme and Aesthetics
#-----------------------------------------------------------------
# The following is automatically inserted by the `kitten themes` command
# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME

# Make transparent with blur
background_opacity 0.75
background_blur 10

# Font
#-----------------------------------------------------------------
# Change default font size
font_size 14

# This was automatically inserted by the `kitten choose-fonts` command.
# The same command can be used to easily change fonts
# BEGIN_KITTY_FONTS
font_family      family="IosevkaTerm Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Cursor
#-----------------------------------------------------------------
# Change cursor to block
shell_integration no-cursor
cursor_shape block

# Window
#-----------------------------------------------------------------
# Initial Window size
remember_window_size no
initial_window_width 1000
initial_window_height 600

# Turn off the confirmation that is required when closing/quitting app.
confirm_os_window_close 0

# Tabs
#-----------------------------------------------------------------
# Set tab bar to top
tab_bar_edge top

# Set tab bar style
tab_bar_style powerline

# Set max tab title width
tab_title_max_length 20

# Map new f1 command to open new tab, but in same CWD
# Default ctrl+shift+t opens new tab in home directory
map f1 launch --cwd=current --type=tab

# Scrollback
#-----------------------------------------------------------------
# Increase limit for number of lines in scrollback history
# Default is 2000, 10000 generally considered a safe default, too big might cause issues
scrollback_lines 10000

# Allow even more history to be stored to disk and loaded using ctrl+shift+h if necessary
# 50MB generally considered a good default, 
scrollback_pager_history_size 50 

# Other
#-----------------------------------------------------------------
# Fix ssh
action_alias ssh kitten ssh

# Use the option key as the meta (alt) key on mac
macos_option_as_alt yes
